name: Deploy Second Game
on:
  push:
    branches: 
      -master
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t keep-white-space:latest .

