name: Deploy Second Game

on:
  push:
    branches: [ master ] # Attention, ta branche s'appelle 'master' sur l'image

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # Pas besoin de "npm install" si tu n'as pas de package.json
      # On vérifie juste que Docker arrive à construire l'image
      - name: Build Docker Image
        run: docker build -t keep-white-space:latest .

      # Déploiement direct sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # On déploie la racine car index.html est ici
          branch: gh-pages